### ISSUE TITLE
[SHOULD] Double tag FIWARE Release 

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/iotagent-opcua#10]
Please add an additional tag to  244d240  to indicate that it was included as part of FIWARE 7.5.1 - you can see a similar examples here:

[IoT Agent JSON](https://github.com/telefonicaid/iotagent-json/releases)
[Wirecloud](https://github.com/Wirecloud/wirecloud/releases)

Please also double tag fbf1516 to indicate that it was included as part of FIWARE 7.5

**Comment by gabrieledeluca** [comment]
Fixed, thank you Jason
