### ISSUE TITLE
Multiple endpoints

### ISSUE THREAD

**Issue by drypatrick** [Engineering-Research-and-Development/iotagent-opcua#100]
As shown in the [performDeviceProvisioning.request.json](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/test/functional/mock/performDeviceProvisioning.request.json), it's possible to specify an endpoint, this means that multiple endpoints are supported? So is it possible to attach the IoT-Agent to multiple devices?

**Comment by walterwootz** [comment]
Hi @drypatrick, unfortunately you can connect the agent only to one device per time. You should instantiate an agent for each of your device.
