### ISSUE TITLE
Remove Node v6

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/iotagent-opcua#2]
(To be addressed in May 2019)

Related to telefonicaid/iotagent-node-lib/issues/700

Node v6 ends support in April 2019 (see https://github.com/nodejs/Release) and should be removed by that date. In particular, this issue involves the following actions:

* engine version should be modified to be >=8 in `packages.json`
* Latest version of `iotagent-node-lib` to be added to package dependencies.

Assuming this component is added to Travis CI, any remaining Node v6 testing should also be removed from `.travis.yml` at this point.

**Comment by gabrieledeluca** [comment]
Thanks @jason-fox, fixed with last commit
