### ISSUE TITLE
IoT Agent version should be updated

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/iotagent-opcua#3]
With the latest release of the IoT Node Agent, the `package.json` of the IoT Agent for OPC-UA should be updated and a new release made.

This keeps the IoT Agent for OPC-UA is alignment with the other IoT Agents and should be completed prior to the FIWARE 7.5.1 release

**Comment by gabrieledeluca** [comment]
Done Jason, many thanks!
