### ISSUE TITLE
support of (metadata) source timestamps

### ISSUE THREAD

**Issue by joriwinderickx-fm** [Engineering-Research-and-Development/iotagent-opcua#42]
I have a basic FIWARE architecture set up that has roughly the following dataflow:

> OPC-UA simulation server -> IoT Agent OPC-UA -> Orion -> QuantumLeap -> CrateDB

The configuration of the IoT agent was based on the examples that were available, though, the IoT Agent does not seem to take into account the timestamp (Source Timestamp) of the value of the node that is configured to be pushed to Orion. Is it supported by the IoT agent e.g. to include this timestamp as a metadata value? If yes, is it documented somewhere on how to configure it?

You can find the configuration that was used for the IoT agent attached:
[config.properties.txt](https://github.com/Engineering-Research-and-Development/iotagent-opcua/files/5665043/config.properties.txt)
[config.json.txt](https://github.com/Engineering-Research-and-Development/iotagent-opcua/files/5665044/config.json.txt)

**Comment by rosieks** [comment]
I would be happy to have that working with NGSI-LD and having `observedAt` value present in the request

**Comment by MattiaMarzano-Eng** [comment]
The support to metadata will be available in the newer version (v2) of the OPC UA Agent that will be released soon. See the dedicated [branch](https://github.com/Engineering-Research-and-Development/iotagent-opcua/tree/iotagent-v2)

**Comment by MattiaMarzano-Eng** [comment]
Agent v2 available on the main branch
