### ISSUE TITLE
Write to a NodeID of basic data type (e.g. Int16) with AccessLevel CurrentWrite.

### ISSUE THREAD

**Issue by trimart** [Engineering-Research-and-Development/iotagent-opcua#49]
In order to write data on an OPC UA server, a suitable method must currently be implemented on the server. This is often not wanted on existing OPC UA server structures. A possibility to write to basic data types with accessLevel CurrentWrite would be an advantage.

**Comment by manfredipist** [comment]
Hello @trimart , as you've already noticed, at moment we don't support this feature but we will try to insert it in our to-do list
