### ISSUE TITLE
[SHOULD] run tests on CI - test suite missing

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/iotagent-opcua#6]
There are currently no CI Tests run on push. 
There is also no badge displaying the current test state on Travis (or equivalent)

```md
<br/>
[![Documentation badge](https://img.shields.io/readthedocs/iotagent-opcua.svg)](https://iotagent-opcua.rtfd.io/)
[![Build badge](https://img.shields.io/travis/Engineering-Research-and-Development/iotagent-opcua.svg)](https://travis-ci.org/Engineering-Research-and-Development/iotagent-opcua/)
![Status](https://nexus.lab.fiware.org/static/badges/statuses/iot-openmtc.svg)
```

You can look in the [IoTagent-LoRaWAN](https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/master/.travis.yml) to see how to set up the `.travis.yml` file.

- displaying CI is a TSC MUST requirement
- running tests on CI is a TSC SHOULD requirement

**Comment by jason-fox** [comment]
Downgraded from MUST to SHOULD since CI is running correctly and a stub exists. #9 

* running tests on CI is a TSC SHOULD requirement

**Comment by gabrieledeluca** [comment]
Basic tests written
