### ISSUE TITLE
 Unable to update/write values in OPCUA Simulated Server using Fiware 

### ISSUE THREAD

**Issue by umerusman34** [Engineering-Research-and-Development/iotagent-opcua#76]
I am trying to do two communication to read and write values from OPCUA Simulated Server using Fiware. I am successful in reading the values from the server.

![Screenshot (48)](https://user-images.githubusercontent.com/106956110/178698753-6c7a7ed4-ef7a-482b-8675-5a515ac3e157.png)
.
 However, I am still facing issues in updating/writing the values. I am using this to update the value. 
```
`{   
    "actionType": "update",
    "entities": [
        
        {
         "id": "age01_7:Simulation",
         "type": "3:Simulation",
         "3:test2": {
            "type": "Number",
            "value": "44",
            "metadata": {}
            
         }
        }
        ]
}`
```

It is working with **http://localhost:1026/v2/op/update** but it only updates the value within the container, not in the Server.
Also, when I try to update using this **http://localhost:4001/v2/op/update** it gives me this error after several minutes

![Screenshot (49)](https://user-images.githubusercontent.com/106956110/178701593-b0b98fc0-f6c9-4a9d-8cd7-6cfc45d4d0e4.png)

**Comment by umerusman34** [comment]
@jason-fox @manfredipist

**Comment by umerusman34** [comment]
@MattiaMarzano-Eng  Thank you for your reply. Can you please elaborate a bit more on what exactly are you suggesting?

_**You can only invoke a method/command from the agent to your server which will do the work you expect**_

**Comment by MattiaMarzano-Eng** [comment]
Taking as example our server where a command "Accelarate" is implemented, you can invoke it from the Context Broker and through the agent is provided to the Server which has the logic to change the variable value "Speed".
![image](https://user-images.githubusercontent.com/33173948/180736403-def574a0-beb9-47d4-a10a-2556ab7c01d6.png)
What you can do in case you have the control on OPC UA server is to implement a command that when is invoked on Context Broker updates accordingly the relative variable in the server.
[Here the example I mentioned from our OPC UA server developed for demo purpose](https://github.com/Engineering-Research-and-Development/opc-ua-car-server/blob/ea63aa4ac5a457bcca5fbfec8bf6e4a7a4471718/Car/Car1/Speed/Speed.js)

**Comment by manfredipist** [comment]
Hi @umerusman34! Please download the latest version of the agent (v2.0.5) which now features OPC UA variables update without command execution (proper get/set methods for the variable will need to be implemented though). Under the given circumstances you will be able to update a variable using the following REST API

PUT http://ORION_ENDPOINT:ORION_PORT/v2/entities/ENTITY_NAME/attrs/ENTITY_ATTRIBUTE?type=ENTITY_TYPE
body:
`{
    "type" : "Number",
    "value" : 5
}`
