### ISSUE TITLE
[MUST] Every GE must have training materials

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/iotagent-opcua#8]
At the moment this enabler has no Tutorial and no link to the Academy and does not fulfil the minimum **Training** section requirements. 

The suggestion is to create a simple *Attaching other IoT Agents tutorial*  to provide a series of simple hello world connections for each agent in turn - this needs to include 

* One docker compose file for base config
* A set of REST API calls to provision the service
* An indication on how to make  minimal measure arrive (e.g. publishing an MQTT topic or equivalent)
* Proof that the data arrives in Orion.

- Presence of training  is a MUST requirement

**Comment by gabrieledeluca** [comment]
Hello @jason-fox, what do you say about [https://iotagent-opcua.readthedocs.io/en/latest/opc_ua_agent_tutorial/index.html](https://iotagent-opcua.readthedocs.io/en/latest/opc_ua_agent_tutorial/index.html)? Thanks

**Comment by jason-fox** [comment]
👍 LGTM. Closing
