### ISSUE TITLE
The tutorial just doesn't work.

### ISSUE THREAD

**Issue by vonbrand** [Engineering-Research-and-Development/iotagent-opcua#88]
There is no port 4001 exposed anywhere, so nothing whatsoever works.

This is Fedora 37-

**Comment by manfredipist** [comment]
Hi @vonbrand 
Please download the iotagent-v2 branch and have a look at the related documentaiton
https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/iotagent-v2/docs/opc_ua_agent_tutorial.md
